### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by jaebradley** [comment]
@DanielRuf thanks for opening up this PR! Will try and take a look in the next couple of days (though I'm traveling so we'll see what type of availability I have).

**Comment by DanielRuf** [comment]
For future PRs: you can normally push to the branch of a PR ;-)

**Comment by jaebradley** [comment]
@DanielRuf thanks for the head's up! I tried but I ran into a permission error (I must've done it wrong 😅 )

**Pull request closed without merging**
